Name: go-gin-setup

Http:
  Host: 127.0.0.1
  Port: 8080

Database:
  Name: setup_db
  Host: localhost
  Port: 5432
  Username: setup_user
  Password: setup_password
  SslMode: disable
  TimeZone: Asia/Jakarta

Auth:
  Enable: true
  TokenExpired: 7200
  IgnorePathPrefixes:
    - /login
    - /register
    - /swagger
    - /posts

Cors:
  AllowOrigins:
    - "*"

Swagger:
  Title: "Go Gin Setup Docs"
  Description: "Collection of Endpoints"
  Version: "1.0"
  DocUrl: "/swagger/*any"