definitions:
  dto.User:
    properties:
      email:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /users/:
    get:
      consumes:
      - application/json
      description: get list users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.User'
            type: array
      summary: List users
      tags:
      - users
swagger: "2.0"
